included:
  - Strata/Sources
  - StrataTests
  - StrataUITests

excluded:
  - .build

opt_in_rules:
  - trailing_comma
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs

disabled_rules: []

force_unwrapping:
  severity: error

implicitly_unwrapped_optional:
  severity: warning
  mode: all_except_iboutlets

trailing_comma:
  mandatory_comma: true

line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

type_name:
  min_length: 2
  max_length: 50

identifier_name:
  min_length: 1
  max_length: 60
  allowed_symbols: ["_"]

reporter: xcode
